### ISSUE TITLE
nice you nabbed vzco.herokuapp

### ISSUE THREAD

**Issue by cjavdev** [jacobhamblin/asco#2]
good domain

**Comment by jacobhamblin** [comment]
I went through two name changes today - ended up with asco, for "aesthetic" instead of "visual" and the upside-down v as an a in the logo. what do you think? Reverting the name or changing it one more time wouldn't be a big deal.

**Comment by jacobhamblin** [comment]
And on the topic of name changes, jacobhamblin or jkh as my github name? k is my middle initial :D
